excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
  - Vendor
  - fastlane
  - .bundle
  - /**/.build
  - SourcePackages
  # As of version 0.43.0, configuration files now consistently have their included/excluded relative file paths aplied relative to their location in the file system.
  - ${PWD}/Pods
  - ${PWD}/Carthage
  - ${PWD}/Vendor
  - ${PWD}/fastlane
  - ${PWD}/.bundle
  - ${PWD}/**/.build
  - ${PWD}/SourcePackages
  - "${PWD}/**/*.generated.swift"

nesting:
  type_level: 3

line_length:
  warning: 120
  error: 120

file_length:
  warning: 800
  error: 1000

type_body_length:
  warning: 500
  error: 600

function_body_length:
  warning: 100
  error: 150

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  allowed_symbols:
    - _

trailing_comma:
  mandatory_comma: true

unused_import:
  require_explicit_imports: false

disabled_rules:
  - identifier_name
  - multiple_closures_with_trailing_closure

custom_rules:
  template_header:
    name: "Default file template header"
    regex: "Copyright .* All rights reserved."
    message: "Remove defailt file template headers"
    severity: error

analyzer_rules:
  - unused_import
  - explicit_self

opt_in_rules:
  - unowned_variable_capture
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - force_unwrapping
  - prohibited_super_call
  - number_separator
  - first_where
  - shorthand_operator
  - fatal_error_message

